// <auto-generated />
using System;
using Catalogo.Infrastructure.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalogo.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogoContext))]
    [Migration("20251211231018_PopulandoBancoComDadosIniciais")]
    partial class PopulandoBancoComDadosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalogo.Domain.Entities.CategoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Descricao = "Lanche"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Descricao = "Acompanhamento"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            Descricao = "Bebida"
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            Descricao = "Sobremesa"
                        });
                });

            modelBuilder.Entity("Catalogo.Domain.Entities.ProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nome");

                    b.HasIndex("Status");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8698),
                            Descricao = "adicional de bacon",
                            Nome = "X-Bacon",
                            Preco = 31.99m,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8707),
                            Descricao = "Zero açucar",
                            Nome = "Coca-Cola",
                            Preco = 7m,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8709),
                            Descricao = "300g",
                            Nome = "Batata frita",
                            Preco = 15m,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8710),
                            Descricao = "Morango",
                            Nome = "Sorvete",
                            Preco = 9m,
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8711),
                            Descricao = "saladinha da boa",
                            Nome = "X-Salada",
                            Preco = 24.99m,
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8712),
                            Descricao = "concorrente",
                            Nome = "Pepsi",
                            Preco = 7m,
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8713),
                            Descricao = "300g",
                            Nome = "Onion rings",
                            Preco = 20m,
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 4,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8714),
                            Descricao = "Chocolate com morango",
                            Nome = "Bolo de pote",
                            Preco = 14m,
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8716),
                            Descricao = "tudo do bom e do melhor",
                            Nome = "X-Tudo",
                            Preco = 40m,
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8717),
                            Descricao = "suquinho",
                            Nome = "Suco de maracuja",
                            Preco = 10m,
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8718),
                            Descricao = "400g",
                            Nome = "Batata + Onion rings P",
                            Preco = 27.5m,
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 4,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8719),
                            Descricao = "Melhor de todos",
                            Nome = "Pudim",
                            Preco = 99m,
                            Status = true
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8720),
                            Descricao = "fitness",
                            Nome = "X-Frango",
                            Preco = 22.99m,
                            Status = true
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8721),
                            Descricao = "pouca gordura graças a Deus",
                            Nome = "X-Calabresa",
                            Preco = 26.99m,
                            Status = true
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8723),
                            Descricao = "suculência ao máximo",
                            Nome = "X-Picanha",
                            Preco = 36.99m,
                            Status = true
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8724),
                            Descricao = "suquinho 2",
                            Nome = "Suco de limão",
                            Preco = 7m,
                            Status = true
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8725),
                            Descricao = "água de torneira",
                            Nome = "H2O",
                            Preco = 5m,
                            Status = true
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8726),
                            Descricao = "700g",
                            Nome = "Batata + Onion rings M",
                            Preco = 33m,
                            Status = true
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 20, 10, 17, 956, DateTimeKind.Local).AddTicks(8727),
                            Descricao = "1Kg",
                            Nome = "Batata + Onion rings G",
                            Preco = 41m,
                            Status = true
                        });
                });

            modelBuilder.Entity("Catalogo.Domain.Entities.ProdutoEntity", b =>
                {
                    b.HasOne("Catalogo.Domain.Entities.CategoriaEntity", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
